apiVersion: apps/v1
kind: Deployment
metadata:
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    control-plane: samplejob-manager
  name: samplejob-manager
  namespace: {{ .Release.Namespace | quote }}
spec:
  replicas: 1
  selector:
    matchLabels: {{- include "common.labels.matchLabels" . | nindent 6 }}
      control-plane: samplejob-manager
  template:
    metadata:
      labels: {{- include "common.labels.standard" . | nindent 8 }}
        control-plane: samplejob-manager
    spec:
      containers:
        - args:
            - --leader-elect
            - --namespace={{ .Release.Namespace | quote }}
          command:
            - /manager
          image: {{ include "common.images.image" ( dict "imageRoot" .Values.sampleset.image "global" .Values.global) }}
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          name: manager
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            limits:
              cpu: 100m
              memory: 300Mi
            requests:
              cpu: 100m
              memory: 20Mi
          securityContext:
            allowPrivilegeEscalation: false
      securityContext:
        runAsUser: 65532
      serviceAccountName: sampleset-sa
      terminationGracePeriodSeconds: 10
