apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app: cache-server
    application-crd-id: kubeflow-pipelines
  name: kubeflow-pipelines-cache-role
  namespace: {{- include "common.names.namespace" . | quote }}
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - watch
      - update
      - patch
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
  - apiGroups:
      - argoproj.io
    resources:
      - workflows
    verbs:
      - get
      - list
      - watch
      - update
      - patch
