apiVersion: v1
kind: ServiceAccount
metadata:
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app: cache-server
    application-crd-id: kubeflow-pipelines
  name: kubeflow-pipelines-cache
  namespace: {{ include "common.names.namespace" . | quote }}
