apiVersion: v1
kind: Service
metadata:
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app: cache-server
    application-crd-id: kubeflow-pipelines
  name: cache-server
  namespace: {{- include "common.names.namespace" . | quote }}
spec:
  ports:
    - port: 443
      targetPort: webhook-api
  selector: {{- include "common.labels.matchLabels" . | nindent 4 }}
    app: cache-server
    application-crd-id: kubeflow-pipelines
