apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: paddlejob-rolebinding
  namespace: {{ .Release.Namespace | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: paddlejob-role
subjects:
  - kind: ServiceAccount
    name: paddlejob-sa
    namespace: {{ .Release.Namespace | quote }}
