apiVersion: v1
entries:
  knative-serving:
  - annotations:
      category: serverless
    apiVersion: v2
    appVersion: 1.2.0
    created: "2022-04-11T18:07:36.663005+08:00"
    dependencies:
    - name: common
      repository: https://charts.bitnami.com/bitnami
      tags:
      - bitnami-common
      version: 1.x.x
    description: Knative Serving builds on Kubernetes to support deploying and serving of applications and functions as serverless containers. Serving is easy to get started with and scales to support advanced scenarios.
    digest: e0a183ddb06f6a35fd79d0221d69d2843e09bc78c4ff98937f59ae75c200605b
    home: https://github.com/knative/serving
    icon: https://knative.dev/docs/images/logo/rgb/knative-logo-rgb.png
    keywords:
    - knative
    - serving
    - serverless
    name: knative-serving
    sources:
    - https://github.com/knative/serving
    type: application
    urls:
    - knative-serving-0.1.0.tgz
    version: 0.1.0
  kubeflow-pipelines:
  - annotations:
      category: pipeline
    apiVersion: v2
    appVersion: 1.7.0
    created: "2022-04-11T18:07:36.683657+08:00"
    dependencies:
    - name: common
      repository: https://charts.bitnami.com/bitnami
      tags:
      - bitnami-common
      version: 1.13.0
    - condition: mysql.enabled
      name: mysql
      repository: https://charts.bitnami.com/bitnami
      version: 8.8.27
    - condition: minio.enabled
      name: minio
      repository: https://charts.bitnami.com/bitnami
      version: 11.1.4
    description: Kubeflow pipelines are reusable end-to-end ML workflows built using the Kubeflow Pipelines SDK.
    digest: 0a588c3d4ebe17085d200178e86beb30e9b296229681fd1dbf6bcb170b970ee4
    home: https://github.com/kubeflow/pipelines
    icon: https://avatars.githubusercontent.com/u/33164907?s=200&v=4
    keywords:
    - kubeflow
    - pipelines
    - workflow
    name: kubeflow-pipelines
    sources:
    - https://github.com/kubeflow/pipelines
    urls:
    - kubeflow-pipelines-0.1.0.tgz
    version: 0.1.0
  paddlecloud:
  - annotations:
      category: mlops
    apiVersion: v2
    appVersion: 0.4.0
    created: "2022-04-11T18:07:36.718939+08:00"
    dependencies:
    - name: common
      repository: https://charts.bitnami.com/bitnami
      tags:
      - bitnami-common
      version: 1.13.0
    - alias: hostpath
      condition: hostpath.enabled
      name: hostpath-provisioner
      repository: https://charts.rimusz.net
      tags:
      - all-dep
      version: 0.2.13
    - alias: juicefs
      condition: juicefs.enabled
      name: juicefs-csi-driver
      repository: https://juicedata.github.io/juicefs-csi-driver/
      tags:
      - all-dep
      version: 0.8.1
    - condition: redis.enabled
      name: redis
      repository: https://charts.bitnami.com/bitnami
      tags:
      - all-dep
      version: 16.5.4
    - alias: jupyterhub
      condition: jupyterhub.enabled
      name: jupyterhub
      repository: https://charts.bitnami.com/bitnami
      tags:
      - all-dep
      version: 1.1.2
    - alias: pipelines
      condition: pipelines.enabled
      name: kubeflow-pipelines
      repository: https://paddleflow-public.hkg.bcebos.com/charts
      tags:
      - all-dep
      version: 0.1.0
    - alias: knative
      condition: knative.enabled
      name: knative-serving
      repository: https://paddleflow-public.hkg.bcebos.com/charts
      tags:
      - all-dep
      version: 0.1.0
    description: PaddlePaddle Docker images and K8s operators for PaddleOCR/Detection developers to use on public/private cloud.
    digest: 8c8db3abaed7576b0ccd1753e949e2dd26c3e43f95fd33d17f329c8705a4b1dc
    home: https://github.com/PaddlePaddle/PaddleCloud
    icon: https://avatars.githubusercontent.com/u/23534030?s=200&v=4
    keywords:
    - paddle
    - PaddlePaddle
    - mlops
    - paddlecloud
    name: paddlecloud
    sources:
    - https://github.com/PaddlePaddle/PaddleCloud
    type: application
    urls:
    - paddlecloud-0.1.0.tgz
    version: 0.1.0
generated: "2022-04-11T18:07:36.65684+08:00"
