apiVersion: v1
entries:
  knative-serving:
  - annotations:
      category: serverless
    apiVersion: v2
    appVersion: 1.2.0
    created: "2022-04-06T14:07:56.429762+08:00"
    dependencies:
    - name: common
      repository: https://charts.bitnami.com/bitnami
      tags:
      - bitnami-common
      version: 1.x.x
    description: Knative Serving builds on Kubernetes to support deploying and serving of applications and functions as serverless containers. Serving is easy to get started with and scales to support advanced scenarios.
    digest: 3558137ba5ec2c61bfca1739a60a051dad7912afe13207a2fa598ea92535dcc6
    home: https://github.com/knative/serving
    icon: https://knative.dev/docs/images/logo/rgb/knative-logo-rgb.png
    keywords:
    - knative
    - serving
    - serverless
    name: knative-serving
    sources:
    - https://github.com/knative/serving
    type: application
    urls:
    - knative-serving-0.1.0.tgz
    version: 0.1.0
  kubeflow-pipelines:
  - annotations:
      category: pipeline
    apiVersion: v2
    appVersion: 1.7.0
    created: "2022-04-06T14:07:56.47233+08:00"
    dependencies:
    - name: common
      repository: https://charts.bitnami.com/bitnami
      tags:
      - bitnami-common
      version: 1.13.0
    - condition: mysql.enabled
      name: mysql
      repository: https://charts.bitnami.com/bitnami
      version: 8.8.27
    - condition: minio.enabled
      name: minio
      repository: https://charts.bitnami.com/bitnami
      version: 11.1.4
    description: Kubeflow pipelines are reusable end-to-end ML workflows built using the Kubeflow Pipelines SDK.
    digest: 66146bcf0008d8966f7fe7a73277536b36f4a8910eb107348c798e4029f877ec
    home: https://github.com/kubeflow/pipelines
    icon: https://avatars.githubusercontent.com/u/33164907?s=200&v=4
    keywords:
    - kubeflow
    - pipelines
    - workflow
    name: kubeflow-pipelines
    sources:
    - https://github.com/kubeflow/pipelines
    urls:
    - kubeflow-pipelines-0.1.0.tgz
    version: 0.1.0
  paddlecloud:
  - annotations:
      category: mlops
    apiVersion: v2
    appVersion: 0.4.0
    created: "2022-04-06T14:07:56.516348+08:00"
    dependencies:
    - name: common
      repository: https://charts.bitnami.com/bitnami
      tags:
      - bitnami-common
      version: 1.13.0
    - alias: hostpath
      condition: hostpath.enabled
      name: hostpath-provisioner
      repository: https://charts.rimusz.net
      tags:
      - all-dep
      version: 0.2.13
    - alias: juicefs
      condition: juicefs.enabled
      name: juicefs-csi-driver
      repository: https://juicedata.github.io/juicefs-csi-driver/
      tags:
      - all-dep
      version: 0.8.1
    - condition: redis.enabled
      name: redis
      repository: https://charts.bitnami.com/bitnami
      tags:
      - all-dep
      version: 16.5.4
    - alias: jupyterhub
      condition: jupyterhub.enabled
      name: jupyterhub
      repository: https://charts.bitnami.com/bitnami
      tags:
      - all-dep
      version: 1.1.2
    - alias: pipelines
      condition: pipelines.enabled
      name: kubeflow-pipelines
      repository: https://paddleflow-public.hkg.bcebos.com/charts
      tags:
      - all-dep
      version: 0.1.0
    - alias: knative
      condition: knative.enabled
      name: knative-serving
      repository: https://paddleflow-public.hkg.bcebos.com/charts
      tags:
      - all-dep
      version: 0.1.0
    description: PaddlePaddle Docker images and K8s operators for PaddleOCR/Detection developers to use on public/private cloud.
    digest: 4cf5f71693d5ca6b30c65562cfa65874daded0b283cdb061f6341f44492cf4e3
    home: https://github.com/PaddlePaddle/PaddleCloud
    icon: https://avatars.githubusercontent.com/u/23534030?s=200&v=4
    keywords:
    - paddle
    - PaddlePaddle
    - mlops
    - paddlecloud
    name: paddlecloud
    sources:
    - https://github.com/PaddlePaddle/PaddleCloud
    type: application
    urls:
    - paddlecloud-0.1.0.tgz
    version: 0.1.0
generated: "2022-04-06T14:07:56.417063+08:00"
