apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: paddle-leader-election-rolebinding
  namespace: {{ .Values.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: paddle-leader-election-role
subjects:
  - kind: ServiceAccount
    name: paddle-manager-sa
    namespace: {{ .Values.namespace }}