{{- if .Values.sampleset.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: samplejob-manager
    {{- include "paddlecloud.labels" . | nindent 4 }}
  name: samplejob-manager
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: samplejob-manager
      {{- include "paddlecloud.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        control-plane: samplejob-manager
        {{- include "paddlecloud.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - args:
            - --leader-elect
            - --namespace={{ .Values.namespace }}
          command:
            - /manager
          image: {{ .Values.sampleset.image }}:{{ .Chart.AppVersion }}
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          name: manager
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            limits:
              cpu: 100m
              memory: 300Mi
            requests:
              cpu: 100m
              memory: 20Mi
          securityContext:
            allowPrivilegeEscalation: false
      securityContext:
        runAsUser: 65532
      terminationGracePeriodSeconds: 10
{{- end }}