apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    application-crd-id: kubeflow-pipelines
  name: application-manager-role
  namespace: {{ include "common.names.namespace" . | quote }}
rules:
  - apiGroups:
      - '*'
    resources:
      - '*'
    verbs:
      - get
      - list
      - update
      - patch
      - watch
  - apiGroups:
      - app.k8s.io
    resources:
      - '*'
    verbs:
      - '*'
