apiVersion: batch/v1
kind: CronJob
metadata:
  name: curl-cronjob
spec:
  schedule: "*/0 0 * * 0"       # It will run at 0:00 in every Sunday
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          serviceAccount: tekton-pipelinerun-cleaner
          containers:
          - name: curl-container
            image: curlimages/curl
            imagePullPolicy: IfNotPresent
            args: ["curl", "-X", "POST", "--data", "{}", "el-cron-listener.default.svc.cluster.local:8080"]
        