apiVersion: v1
kind: ServiceAccount
metadata:
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    application-crd-id: kubeflow-pipelines
  name: kubeflow-pipelines-viewer
  namespace: {{- include "common.names.namespace" . | quote }}
