# permissions for end users to edit paddlejobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: paddlejob-editor-role
rules:
- apiGroups:
  - batch.paddlepaddle.org
  resources:
  - paddlejobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch.paddlepaddle.org
  resources:
  - paddlejobs/status
  verbs:
  - get
