apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: paddle-cloud
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: paddle-cloud
    spec:
      volumes:
      - name: cert-volume
        hostPath:
          path: /root/wuyi/certs
      - name: settings
        hostPath:
          path: /root/wuyi/settings.py
      containers:
      - name: paddle-cloud
        imagePullPolicy: Always
        image: docker.paddlepaddlehub.com/pcloud:wuyi_test
        volumeMounts:
        - name: cert-volume
          mountPath: /certs
        - name: settings
          mountPath: /pcloud/paddlecloud/settings.py
        ports:
        - containerPort: 8000
      nodeSelector:
        pcloud: pcloud
