apiVersion: batch/v1
kind: Job
metadata:
  name: prepare-cloud-dataset
spec:
  template:
    metadata:
      name: prepare-cloud-dataset
    spec:
      volumes:
        - name: data-storage
          cephfs:
            monitors:
              - 192.168.16.23:6789
            path: "/public"
            user: "admin"
            secretRef:
              name: ceph-secret
      containers:
      - name: prepare
        image: yancey1989/paddlecloud-job
        command: ["sh", "-c", "python -c \"import paddle.v2.dataset as dataset; dataset.common.convert('/pfs/dlnel/public/dataset')\""]
        volumeMounts:
        - name: data-storage
          mountPath: /pfs/dlnel/public
      restartPolicy: Never
