apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: auto-build-pipelinerun
spec:
  serviceAccountName: tekton-triggers-example-sa
  pipelineRef:
    name: auto-build-pipeline
  workspaces:
  - name: shared-data
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
  params:
  - name: toolkit-repo-name
    value: PaddleOCR
  - name: toolkit-revision
    value: release/2.4
  - name: toolkit-base-image-tag
    value: 2.2.2
  - name: toolkit-env
    value: cpu            # gpu / cpu
  - name: docker-repo-url
    value: https://github.com/freeliuzc/PaddleCloud.git
  - name: docker-revision
    value: dev-tekton
  - name: dockerfile-path
    value: tekton/dockerfiles/Dockerfile
  - name: image-registry
    value: paddlecloud/paddleocr
# - name: kaniko-image
#   value: gcr.io/kaniko-project/executor:latest


  
    