{{- if .Values.sampleset.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sampleset-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sampleset-clusterrole
subjects:
  - kind: ServiceAccount
    name: sampleset-sa
    namespace: {{ .Release.Namespace | quote }}
{{- end -}}
