{{- if .Values.sampleset.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ printf "%s-sampleset-clusterrolebinding" (include "common.names.fullname" .) }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ printf "%s-sampleset-clusterrole" (include "common.names.fullname" .) }}
subjects:
  - kind: ServiceAccount
    name: sampleset-sa
    namespace: {{ .Release.Namespace | quote }}
{{- end -}}
