{{- if or (index .Values.tags "all-dep" ) (and .Values.pipelines.enabled .Values.redis.enabled) -}}
apiVersion: v1
kind: Secret
metadata:
  name: data-center
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
type: Opaque
data:
  name: "ZGF0YS1jZW50ZXI="
  metaurl: {{ include "paddlecloud.juicefs.metaurl" . | b64enc | quote }}
  storage: "bWluaW8="
  access-key: {{ .Values.pipelines.minio.auth.rootUser | b64enc | quote }}
  secret-key: {{ .Values.pipelines.minio.auth.rootPassword | b64enc | quote }}
  bucket: {{ include "paddlecloud.juicefs.bucket" . | b64enc | quote }}
{{- end }}
