{{- if or .Values.tags.all-dep (and .Values.pipelines.enabled .Values.redis.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: data-center
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
type: Opaque
data:
  name: ""
  metaurl: {{ printf "redis://%s:%s@%s:%s" | b64enc | quote }}
  storage: minio
  {{- if .accessKey }}
  access-key: {{ .accessKey | b64enc | quote }}
  {{- end }}
  {{- if .secretKey }}
  secret-key: {{ .secretKey | b64enc | quote }}
  {{- end }}
  bucket: {{ .bucket | b64enc | quote }}

{{- end }}