apiVersion: v1
kind: Secret
metadata:
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    application-crd-id: kubeflow-pipelines
  name: mlpipeline-minio-artifact
  namespace: {{- include "common.names.namespace" . | quote }}
stringData:
  accesskey: minio
  secretkey: minio123
