apiVersion: v1
kind: Secret
metadata:
  labels:
    application-crd-id: kubeflow-pipelines
  name: mlpipeline-minio-artifact
  namespace: {{ include "common.names.namespace" . | quote }}
stringData:
  accesskey: {{ .Values.minio.auth.rootUser }}
  secretkey: {{ .Values.minio.auth.rootPassword }}
