## @section Global parameters
## Global Docker image parameters
## Please, note that this will override the image parameters, including dependencies, configured to use the global value
## Current available global Docker image parameters: imageRegistry, imagePullSecrets and storageClass

## @param global.imageRegistry Global Docker image registry
## @param global.imagePullSecrets [array] Global Docker registry secret names as an array
## @param global.storageClass Global StorageClass for Persistent Volume(s)
##
global:
  imageRegistry: ""
  ## E.g.
  ## imagePullSecrets:
  ##   - myRegistryKeySecretName
  ##
  imagePullSecrets: []
  storageClass: ""


## @param kubeVersion Override Kubernetes version
##
kubeVersion: ""
## @param nameOverride String to partially override common.names.fullname
##
nameOverride: ""
## @param fullnameOverride String to fully override common.names.fullname
##
fullnameOverride: ""
## @param commonLabels Labels to add to all deployed objects
##
commonLabels: {}
## @param commonAnnotations Annotations to add to all deployed objects
##
commonAnnotations: {}
## @param clusterDomain Kubernetes cluster domain name
##
clusterDomain: cluster.local
## @param extraDeploy Array of extra objects to deploy with the release
##`
extraDeploy: []


activator:
  image:
    registry: registry.baidubce.com
    repository: paddleflow-public/knative-serving-activator
    tag: 246171
    ## Specify a imagePullPolicy
    ## Defaults to 'Always' if image tag is 'latest', else set to 'IfNotPresent'
    ## ref: https://kubernetes.io/docs/user-guide/images/#pre-pulling-images
    ##
    pullPolicy: IfNotPresent
    ## Optionally specify an array of imagePullSecrets.
    ## Secrets must be manually created in the namespace.
    ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
    ## e.g:
    ## pullSecrets:
    ##   - myRegistryKeySecretName
    ##
    pullSecrets: [ ]
    ## Enable debug mode
    ##
    debug: false


autoscaler:
  image:
    registry: registry.baidubce.com
    repository: paddleflow-public/knative-serving-autoscaler
    tag: 9ed4c3
    ## Specify a imagePullPolicy
    ## Defaults to 'Always' if image tag is 'latest', else set to 'IfNotPresent'
    ## ref: https://kubernetes.io/docs/user-guide/images/#pre-pulling-images
    ##
    pullPolicy: IfNotPresent
    ## Optionally specify an array of imagePullSecrets.
    ## Secrets must be manually created in the namespace.
    ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
    ## e.g:
    ## pullSecrets:
    ##   - myRegistryKeySecretName
    ##
    pullSecrets: [ ]
    ## Enable debug mode
    ##
    debug: false

controller:
  image:
    registry: registry.baidubce.com
    repository: paddleflow-public/knative-serving-controller
    tag: 8e8b9e
    ## Specify a imagePullPolicy
    ## Defaults to 'Always' if image tag is 'latest', else set to 'IfNotPresent'
    ## ref: https://kubernetes.io/docs/user-guide/images/#pre-pulling-images
    ##
    pullPolicy: IfNotPresent
    ## Optionally specify an array of imagePullSecrets.
    ## Secrets must be manually created in the namespace.
    ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
    ## e.g:
    ## pullSecrets:
    ##   - myRegistryKeySecretName
    ##
    pullSecrets: [ ]
    ## Enable debug mode
    ##
    debug: false

crds:

domainMapping:
  domainMapping:
    image:
      registry: registry.baidubce.com
      repository: paddleflow-public/domain-mapping
      tag: bd78aa
      ## Specify a imagePullPolicy
      ## Defaults to 'Always' if image tag is 'latest', else set to 'IfNotPresent'
      ## ref: https://kubernetes.io/docs/user-guide/images/#pre-pulling-images
      ##
      pullPolicy: IfNotPresent
      ## Optionally specify an array of imagePullSecrets.
      ## Secrets must be manually created in the namespace.
      ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
      ## e.g:
      ## pullSecrets:
      ##   - myRegistryKeySecretName
      ##
      pullSecrets: [ ]
      ## Enable debug mode
      ##
      debug: false
  domainMappingWebhook:
    image:
      registry: registry.baidubce.com
      repository: paddleflow-public/domain-mapping-webhook
      tag: 3892bc
      ## Specify a imagePullPolicy
      ## Defaults to 'Always' if image tag is 'latest', else set to 'IfNotPresent'
      ## ref: https://kubernetes.io/docs/user-guide/images/#pre-pulling-images
      ##
      pullPolicy: IfNotPresent
      ## Optionally specify an array of imagePullSecrets.
      ## Secrets must be manually created in the namespace.
      ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
      ## e.g:
      ## pullSecrets:
      ##   - myRegistryKeySecretName
      ##
      pullSecrets: [ ]
      ## Enable debug mode
      ##
      debug: false


kourier:
  netKourierController:
    image:
      registry: registry.baidubce.com
      repository: paddleflow-public/kourier
      tag: 5ec9c4
      ## Specify a imagePullPolicy
      ## Defaults to 'Always' if image tag is 'latest', else set to 'IfNotPresent'
      ## ref: https://kubernetes.io/docs/user-guide/images/#pre-pulling-images
      ##
      pullPolicy: IfNotPresent
      ## Optionally specify an array of imagePullSecrets.
      ## Secrets must be manually created in the namespace.
      ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
      ## e.g:
      ## pullSecrets:
      ##   - myRegistryKeySecretName
      ##
      pullSecrets: [ ]
      ## Enable debug mode
      ##
      debug: false
  threeScaleKourierGateway:
    image:
      registry: registry.baidubce.com
      repository: paddleflow-public/envoy
      tag: v1.16
      ## Specify a imagePullPolicy
      ## Defaults to 'Always' if image tag is 'latest', else set to 'IfNotPresent'
      ## ref: https://kubernetes.io/docs/user-guide/images/#pre-pulling-images
      ##
      pullPolicy: IfNotPresent
      ## Optionally specify an array of imagePullSecrets.
      ## Secrets must be manually created in the namespace.
      ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
      ## e.g:
      ## pullSecrets:
      ##   - myRegistryKeySecretName
      ##
      pullSecrets: [ ]
      ## Enable debug mode
      ##
      debug: false


netIstio:
  image:
    registry: registry.baidubce.com
    repository: paddleflow-public/net-istio-controller
    tag: bef57a
    ## Specify a imagePullPolicy
    ## Defaults to 'Always' if image tag is 'latest', else set to 'IfNotPresent'
    ## ref: https://kubernetes.io/docs/user-guide/images/#pre-pulling-images
    ##
    pullPolicy: IfNotPresent
    ## Optionally specify an array of imagePullSecrets.
    ## Secrets must be manually created in the namespace.
    ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
    ## e.g:
    ## pullSecrets:
    ##   - myRegistryKeySecretName
    ##
    pullSecrets: [ ]
    ## Enable debug mode
    ##
    debug: false


webhook:
  image:
    registry: registry.baidubce.com
    repository: paddleflow-public/knative-serving-webhook
    tag: 0f12dc
    ## Specify a imagePullPolicy
    ## Defaults to 'Always' if image tag is 'latest', else set to 'IfNotPresent'
    ## ref: https://kubernetes.io/docs/user-guide/images/#pre-pulling-images
    ##
    pullPolicy: IfNotPresent
    ## Optionally specify an array of imagePullSecrets.
    ## Secrets must be manually created in the namespace.
    ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
    ## e.g:
    ## pullSecrets:
    ##   - myRegistryKeySecretName
    ##
    pullSecrets: [ ]
    ## Enable debug mode
    ##
    debug: false


config:
  network:
    data: |
      ################################
      #                              #
      #    EXAMPLE CONFIGURATION     #
      #                              #
      ################################

      # This block is not actually functional configuration,
      # but serves to illustrate the available configuration
      # options and document them in a way that is accessible
      # to users that `kubectl edit` this config map.
      #
      # These sample configuration options may be copied out of
      # this example block and unindented to be in the data block
      # to actually change the configuration.

      # ingress.class specifies the default ingress class
      # to use when not dictated by Route annotation.
      #
      # If not specified, will use the Istio ingress.
      #
      # Note that changing the Ingress class of an existing Route
      # will result in undefined behavior.  Therefore it is best to only
      # update this value during the setup of Knative, to avoid getting
      # undefined behavior.
      ingress.class: "istio.ingress.networking.knative.dev"

      # certificate.class specifies the default Certificate class
      # to use when not dictated by Route annotation.
      #
      # If not specified, will use the Cert-Manager Certificate.
      #
      # Note that changing the Certificate class of an existing Route
      # will result in undefined behavior.  Therefore it is best to only
      # update this value during the setup of Knative, to avoid getting
      # undefined behavior.
      certificate.class: "cert-manager.certificate.networking.knative.dev"

      # domainTemplate specifies the golang text template string to use
      # when constructing the Knative service's DNS name. The default
      # value is "{{.Name}}.{{.Namespace}}.{{.Domain}}".
      #
      # Valid variables defined in the template include Name, Namespace, Domain,
      # Labels, and Annotations. Name will be the result of the tagTemplate
      # below, if a tag is specified for the route.
      #
      # Changing this value might be necessary when the extra levels in
      # the domain name generated is problematic for wildcard certificates
      # that only support a single level of domain name added to the
      # certificate's domain. In those cases you might consider using a value
      # of "{{.Name}}-{{.Namespace}}.{{.Domain}}", or removing the Namespace
      # entirely from the template. When choosing a new value be thoughtful
      # of the potential for conflicts - for example, when users choose to use
      # characters such as `-` in their service, or namespace, names.
      # {{.Annotations}} or {{.Labels}} can be used for any customization in the
      # go template if needed.
      # We strongly recommend keeping namespace part of the template to avoid
      # domain name clashes:
      # eg. '{{.Name}}-{{.Namespace}}.{{ index .Annotations "sub"}}.{{.Domain}}'
      # and you have an annotation {"sub":"foo"}, then the generated template
      # would be {Name}-{Namespace}.foo.{Domain}
      domainTemplate: "{{.Name}}.{{.Namespace}}.{{.Domain}}"

      # tagTemplate specifies the golang text template string to use
      # when constructing the DNS name for "tags" within the traffic blocks
      # of Routes and Configuration.  This is used in conjunction with the
      # domainTemplate above to determine the full URL for the tag.
      tagTemplate: "{{.Tag}}-{{.Name}}"

      # Controls whether TLS certificates are automatically provisioned and
      # installed in the Knative ingress to terminate external TLS connection.
      # 1. Enabled: enabling auto-TLS feature.
      # 2. Disabled: disabling auto-TLS feature.
      autoTLS: "Disabled"

      # Controls the behavior of the HTTP endpoint for the Knative ingress.
      # It requires autoTLS to be enabled.
      # 1. Enabled: The Knative ingress will be able to serve HTTP connection.
      # 2. Disabled: The Knative ingress will reject HTTP traffic.
      # 3. Redirected: The Knative ingress will send a 302 redirect for all
      # http connections, asking the clients to use HTTPS.
      httpProtocol: "Enabled"

      # rolloutDuration contains the minimal duration in seconds over which the
      # Configuration traffic targets are rolled out to the newest revision.
      rolloutDuration: "0"

      # autocreateClusterDomainClaims controls whether ClusterDomainClaims should
      # be automatically created (and deleted) as needed when DomainMappings are
      # reconciled.
      #
      # If this is "false", the cluster administrator is responsible for creating
      # ClusterDomainClaims and delegating them to namespaces via their
      # spec.Namespace field. This is useful for multitenant environments
      # which need to control which namespace can use a particular domain name in
      # a domain mapping.
      autocreateClusterDomainClaims: "true"
  observability:
    data: |
      ################################
      #                              #
      #    EXAMPLE CONFIGURATION     #
      #                              #
      ################################
  
      # This block is not actually functional configuration,
      # but serves to illustrate the available configuration
      # options and document them in a way that is accessible
      # to users that `kubectl edit` this config map.
      #
      # These sample configuration options may be copied out of
      # this example block and unindented to be in the data block
      # to actually change the configuration.
  
      # logging.enable-var-log-collection defaults to false.
      # The fluentd daemon set will be set up to collect /var/log if
      # this flag is true.
      logging.enable-var-log-collection: "false"
  
      # logging.revision-url-template provides a template to use for producing the
      # logging URL that is injected into the status of each Revision.
      logging.revision-url-template: "http://logging.example.com/?revisionUID=${REVISION_UID}"
  
      # If non-empty, this enables queue proxy writing user request logs to stdout, excluding probe
      # requests.
      # NB: after 0.18 release logging.enable-request-log must be explicitly set to true
      # in order for request logging to be enabled.
      #
      # The value determines the shape of the request logs and it must be a valid go text/template.
      # It is important to keep this as a single line. Multiple lines are parsed as separate entities
      # by most collection agents and will split the request logs into multiple records.
      #
      # The following fields and functions are available to the template:
      #
      # Request: An http.Request (see https://golang.org/pkg/net/http/#Request)
      # representing an HTTP request received by the server.
      #
      # Response:
      # struct {
      #   Code    int       // HTTP status code (see https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml)
      #   Size    int       // An int representing the size of the response.
      #   Latency float64   // A float64 representing the latency of the response in seconds.
      # }
      #
      # Revision:
      # struct {
      #   Name          string  // Knative revision name
      #   Namespace     string  // Knative revision namespace
      #   Service       string  // Knative service name
      #   Configuration string  // Knative configuration name
      #   PodName       string  // Name of the pod hosting the revision
      #   PodIP         string  // IP of the pod hosting the revision
      # }
      #
      logging.request-log-template: '{"httpRequest": {"requestMethod": "{{.Request.Method}}", "requestUrl": "{{js .Request.RequestURI}}", "requestSize": "{{.Request.ContentLength}}", "status": {{.Response.Code}}, "responseSize": "{{.Response.Size}}", "userAgent": "{{js .Request.UserAgent}}", "remoteIp": "{{js .Request.RemoteAddr}}", "serverIp": "{{.Revision.PodIP}}", "referer": "{{js .Request.Referer}}", "latency": "{{.Response.Latency}}s", "protocol": "{{.Request.Proto}}"}, "traceId": "{{index .Request.Header "X-B3-Traceid"}}"}'
  
      # If true, the request logging will be enabled.
      # NB: up to and including Knative version 0.18 if logging.request-log-template is non-empty, this value
      # will be ignored.
      logging.enable-request-log: "false"
  
      # If true, this enables queue proxy writing request logs for probe requests to stdout.
      # It uses the same template for user requests, i.e. logging.request-log-template.
      logging.enable-probe-request-log: "false"
  
      # metrics.backend-destination field specifies the system metrics destination.
      # It supports either prometheus (the default) or stackdriver.
      # Note: Using stackdriver will incur additional charges
      metrics.backend-destination: prometheus
  
      # metrics.request-metrics-backend-destination specifies the request metrics
      # destination. It enables queue proxy to send request metrics.
      # Currently supported values: prometheus (the default), stackdriver.
      metrics.request-metrics-backend-destination: prometheus
  
      # metrics.stackdriver-project-id field specifies the stackdriver project ID. This
      # field is optional. When running on GCE, application default credentials will be
      # used if this field is not provided.
      metrics.stackdriver-project-id: "<your stackdriver project id>"
  
      # metrics.allow-stackdriver-custom-metrics indicates whether it is allowed to send metrics to
      # Stackdriver using "global" resource type and custom metric type if the
      # metrics are not supported by "knative_revision" resource type. Setting this
      # flag to "true" could cause extra Stackdriver charge.
      # If metrics.backend-destination is not Stackdriver, this is ignored.
      metrics.allow-stackdriver-custom-metrics: "false"
  
      # profiling.enable indicates whether it is allowed to retrieve runtime profiling data from
      # the pods via an HTTP server in the format expected by the pprof visualization tool. When
      # enabled, the Knative Serving pods expose the profiling data on an alternate HTTP port 8008.
      # The HTTP context root for profiling is then /debug/pprof/.
      profiling.enable: "false"