apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-kaniko
spec:
  resources:
    requests:
      storage: 8Gi
  volumeMode: Filesystem
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  selector:
    matchLabels:
      pv: kaniko
