apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    application-crd-id: kubeflow-pipelines
    control-plane: controller-manager
    controller-tools.k8s.io: "1.0"
  name: controller-manager
  namespace: kubeflow
spec:
  selector:
    matchLabels:
      application-crd-id: kubeflow-pipelines
      control-plane: controller-manager
      controller-tools.k8s.io: "1.0"
  template:
    metadata:
      labels:
        application-crd-id: kubeflow-pipelines
        control-plane: controller-manager
        controller-tools.k8s.io: "1.0"
    spec:
      containers:
        - command:
            - /bin/sh
            - -c
            - |
              echo "logs are hidden because volume is too excessive" &&
              /root/manager 2> /dev/null
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: registry.baidubce.com/paddleflow-public/application-crd-controller:1.0-beta-non-cluster-role
          imagePullPolicy: IfNotPresent
          name: manager
          resources:
            limits:
              cpu: 100m
              memory: 30Mi
            requests:
              cpu: 100m
              memory: 20Mi
      serviceAccountName: application