apiVersion: v1
kind: Service
metadata:
  labels:
    application-crd-id: kubeflow-pipelines
    control-plane: controller-manager
    controller-tools.k8s.io: "1.0"
  name: controller-manager-service
  namespace: kubeflow
spec:
  ports:
    - port: 443
  selector:
    application-crd-id: kubeflow-pipelines
    control-plane: controller-manager
    controller-tools.k8s.io: "1.0"