apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: cron-listener
  annotations:
    tekton.dev/payload-validation: "false"
spec:
  serviceAccountName: tekton-triggers-example-sa
  triggers:
  - name: cron-trig
    bindings:
    - ref: cron-binding
    template:
      ref: cron-template

---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: cron-template
spec:
  params:
  - name: key
    description: Example of spec.
    default: value
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: auto-build-pipelinerun-
    spec:
      serviceAccountName: tekton-triggers-example-sa
      pipelineRef:
        name: auto-build-pipeline
      workspaces:
      - name: shared-data
        volumeClaimTemplate:
          spec:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 10Gi
      params:
      - name: toolkit-repo-name
        value: PaddleOCR
      - name: toolkit-revision      # (branch, tag, sha, ref, etc...)
        value: release/2.3
      - name: toolkit-base-image-tag
        value: 2.2.2
      - name: docker-repo-url
        value: https://github.com/freeliuzc/PaddleCloud.git
      - name: docker-revision      # (branch, tag, sha, ref, etc...)
        value: main
      - name: dockerfile-path
        value: images/tekton/dockerfiles/paddleocr/Dockerfile.cpu
      - name: image-registry
        value: paddlecloud/paddleocr

---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: cron-binding
spec:
  params:
  - name: key
    value: value

