apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ printf "%s-cache-deployer-clusterrolebinding" (include "common.names.fullname" .) }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ printf "%s-cache-deployer-clusterrole" (include "common.names.fullname" .) }}
subjects:
  - kind: ServiceAccount
    name: kubeflow-pipelines-cache-deployer-sa
    namespace: {{- include "common.names.namespace" . | quote }}
