apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    application-crd-id: kubeflow-pipelines
    component: metadata-envoy
  name: {{ printf "%s-metadata-envoy" (include "common.names.fullname" .) }}
  namespace: {{ include "common.names.namespace" . | quote }}
spec:
  replicas: 1
  selector:
    matchLabels:
      application-crd-id: kubeflow-pipelines
      component: metadata-envoy
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        application-crd-id: kubeflow-pipelines
        component: metadata-envoy
    spec:
      containers:
        - image: {{ include "common.images.image" (dict "imageRoot" .Values.metadataEnvoy.image "global" .Values.global) }}
          imagePullPolicy: {{ .Values.metadataEnvoy.image.pullPolicy | quote }}
          name: container
          ports:
            - containerPort: 9090
              name: md-envoy
            - containerPort: 9901
              name: envoy-admin
