apiVersion: v1
kind: Service
metadata:
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app: metadata-envoy
    application-crd-id: kubeflow-pipelines
  name: metadata-envoy-service
  namespace: {{ include "common.names.namespace" . | quote }}
spec:
  ports:
    - name: md-envoy
      port: 9090
      protocol: TCP
  selector: {{- include "common.labels.matchLabels" . | nindent 4 }}
    application-crd-id: kubeflow-pipelines
    component: metadata-envoy
  type: ClusterIP
