apiVersion: apps/v1
kind: Deployment
metadata:
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app: ml-pipeline-persistenceagent
    application-crd-id: kubeflow-pipelines
  name: {{ printf "%s-persistenceagent" (include "common.names.fullname" .) }}
  namespace: {{ include "common.names.namespace" . | quote }}
spec:
  selector:
    matchLabels: {{- include "common.labels.matchLabels" . | nindent 6 }}
      app: ml-pipeline-persistenceagent
      application-crd-id: kubeflow-pipelines
  template:
    metadata:
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
      labels: {{- include "common.labels.matchLabels" . | nindent 8 }}
        app: ml-pipeline-persistenceagent
        application-crd-id: kubeflow-pipelines
    spec:
      containers:
        - env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: TTL_SECONDS_AFTER_WORKFLOW_FINISH
              value: "86400"
            - name: NUM_WORKERS
              value: "2"
          image: {{ include "common.images.image" (dict "imageRoot" .Values.persistenceagent.image "global" .Values.global) }}
          imagePullPolicy: {{ .Values.persistenceagent.image.pullPolicy | quote }}
          name: ml-pipeline-persistenceagent
          resources:
            requests:
              cpu: 120m
              memory: 500Mi
      serviceAccountName: ml-pipeline-persistenceagent
