apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    application-crd-id: kubeflow-pipelines
  name: ml-pipeline-persistenceagent-role
  namespace: {{- include "common.names.namespace" . | quote }}
rules:
  - apiGroups:
      - argoproj.io
    resources:
      - workflows
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - kubeflow.org
    resources:
      - scheduledworkflows
    verbs:
      - get
      - list
      - watch
