apiVersion: v1
kind: ConfigMap
metadata:
  name: config-network
  namespace: knative-serving
  labels:
    serving.knative.dev/release: "v0.21.1"
  annotations:
    knative.dev/example-checksum: "14cd8fa3"
data:
  _example: |
    {{.Values.config.network.data | toString | nindent 4}}
