apiVersion: v1
kind: ConfigMap
metadata:
  name: config-observability
  namespace: knative-serving
  labels:
    serving.knative.dev/release: "v0.21.1"
  annotations:
    knative.dev/example-checksum: "97c1d10b"
data:
  _example: |
    {{ .Values.config.observability.data | toString | nindent 4}}
