apiVersion: caching.internal.knative.dev/v1alpha1
kind: Image
metadata:
  name: queue-proxy
  namespace: knative-serving
  labels:
    serving.knative.dev/release: "v0.21.1"
spec:
  # This is the Go import path for the binary that is containerized
  # and substituted here.
  image: registry.baidubce.com/paddleflow-public/knative-serving-queue:b082cf
