apiVersion: v1
data:
  artifactRepository: |
    archiveLogs: true
    s3:
      endpoint: {{ include "pipeline.minio.endpoint" . | quote }}
      bucket: "mlpipeline"
      keyFormat: {{ .Values.workflow.keyFormat | toString | quote }}
      insecure: true
      accessKeySecret:
        name: mlpipeline-minio-artifact
        key: accesskey
      secretKeySecret:
        name: mlpipeline-minio-artifact
        key: secretkey
  containerRuntimeExecutor: docker
  executor: |
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 0.01
        memory: 32Mi
      limits:
        cpu: 0.5
        memory: 512Mi
kind: ConfigMap
metadata:
  labels:
    application-crd-id: kubeflow-pipelines
  name: workflow-controller-configmap
  namespace: {{ include "common.names.namespace" . | quote }}
