apiVersion: v1
kind: Service
metadata:
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app: workflow-controller
    application-crd-id: kubeflow-pipelines
  name: workflow-controller-metrics
  namespace: {{ include "common.names.namespace" . | quote }}
spec:
  ports:
    - name: metrics
      port: 9090
      protocol: TCP
      targetPort: 9090
  selector: {{- include "common.labels.matchLabels" . | nindent 4 }}
    app: workflow-controller
    application-crd-id: kubeflow-pipelines
