apiVersion: v1
kind: Service
metadata:
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    application-crd-id: kubeflow-pipelines
  name: ml-pipeline
  namespace: {{- include "common.names.namespace" . | quote }}
spec:
  ports:
    - name: http
      port: 8888
      protocol: TCP
      targetPort: 8888
    - name: grpc
      port: 8887
      protocol: TCP
      targetPort: 8887
  selector: {{- include "common.labels.matchLabels" . | nindent 4 }}
    app: ml-pipeline
    application-crd-id: kubeflow-pipelines
