apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: paddle-leader-election-role
  namespace: {{ .Release.Namespace | quote }}
rules:
  - apiGroups:
      - ""
      - coordination.k8s.io
    resources:
      - configmaps
      - leases
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch