apiVersion: apps/v1
kind: Deployment
metadata:
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app: ml-pipeline-visualizationserver
    application-crd-id: kubeflow-pipelines
  name: {{ printf "%s-visualizationserver" (include "common.names.fullname" .) }}
  namespace: {{ include "common.names.namespace" . | quote }}
spec:
  selector:
    matchLabels: {{- include "common.labels.matchLabels" . | nindent 6 }}
      app: ml-pipeline-visualizationserver
      application-crd-id: kubeflow-pipelines
  template:
    metadata:
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
      labels: {{- include "common.labels.matchLabels" . | nindent 8 }}
        app: ml-pipeline-visualizationserver
        application-crd-id: kubeflow-pipelines
    spec:
      containers:
        - image: {{ include "common.images.image" (dict "imageRoot" .Values.visualizationserver.image "global" .Values.global) }}
          imagePullPolicy: {{ .Values.visualizationserver.image.pullPolicy | quote }}
          livenessProbe:
            exec:
              command:
                - wget
                - -q
                - -S
                - -O
                - '-'
                - http://localhost:8888/
            initialDelaySeconds: 3
            periodSeconds: 5
            timeoutSeconds: 2
          name: ml-pipeline-visualizationserver
          ports:
            - containerPort: 8888
              name: http
          readinessProbe:
            exec:
              command:
                - wget
                - -q
                - -S
                - -O
                - '-'
                - http://localhost:8888/
            initialDelaySeconds: 3
            periodSeconds: 5
            timeoutSeconds: 2
          resources:
            requests:
              cpu: 30m
              memory: 500Mi
      serviceAccountName: ml-pipeline-visualizationserver
