apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    application-crd-id: kubeflow-pipelines
  name: ml-pipeline-visualizationserver
  namespace: {{ include "common.names.namespace" . | quote }}
