apiVersion: v1
kind: Service
metadata:
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    application-crd-id: kubeflow-pipelines
    control-plane: controller-manager
    controller-tools.k8s.io: "1.0"
  name: controller-manager-service
  namespace: {{- include "common.names.namespace" . | quote }}
spec:
  ports:
    - port: 443
  selector: {{- include "common.labels.matchLabels" . | nindent 4 }}
    application-crd-id: kubeflow-pipelines
    control-plane: controller-manager
    controller-tools.k8s.io: "1.0"
