{{- if .Values.paddlejob.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ printf "%s-paddlejob-clusterrole" (include "common.names.fullname" .) }}
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
      - list
      - watch
{{- end -}}
