{{- if .Values.paddlejob.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ printf "%s-paddlejob-clusterrolebinding" (include "common.names.fullname" .) }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ printf "%s-paddlejob-clusterrole" (include "common.names.fullname" .) }}
subjects:
  - kind: ServiceAccount
    name: paddlejob-sa
    namespace: {{ .Release.Namespace | quote }}
{{- end -}}
