{{- if .Values.proxyAgent.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    application-crd-id: kubeflow-pipelines
  name: inverse-proxy-config
  namespace: {{ include "common.names.namespace" . | quote }}
{{- end -}}
