apiVersion: v1
kind: ConfigMap
metadata:
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    application-crd-id: kubeflow-pipelines
  name: inverse-proxy-config
  namespace: {{- include "common.names.namespace" . | quote }}
