{{- if .Values.proxyAgent.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: proxy-agent
    application-crd-id: kubeflow-pipelines
  name: {{ printf "%s-proxy-agent" (include "common.names.fullname" .) }}
  namespace: {{ include "common.names.namespace" . | quote }}
spec:
  selector:
    matchLabels:
      app: proxy-agent
      application-crd-id: kubeflow-pipelines
  template:
    metadata:
      labels:
        app: proxy-agent
        application-crd-id: kubeflow-pipelines
    spec:
      containers:
        - image: {{ include "common.images.image" (dict "imageRoot" .Values.proxyAgent.image "global" .Values.global) }}
          imagePullPolicy: {{ .Values.proxyAgent.image.pullPolicy | quote }}
          name: proxy-agent
      hostNetwork: true
      serviceAccountName: proxy-agent-runner
{{- end -}}
