apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app: proxy-agent-runner
    application-crd-id: kubeflow-pipelines
  name: proxy-agent-runner
  namespace: kubeflow
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - '*'