apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app: proxy-agent-runner
    application-crd-id: kubeflow-pipelines
  name: proxy-agent-runner
  namespace: {{ include "common.names.namespace" . | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: proxy-agent-runner
subjects:
  - kind: ServiceAccount
    name: proxy-agent-runner
    namespace: {{ include "common.names.namespace" . | quote }}
