apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app: proxy-agent-runner
    application-crd-id: kubeflow-pipelines
  name: proxy-agent-runner
  namespace: {{ include "common.names.namespace" . | quote }}
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - '*'
