apiVersion: v1
kind: ServiceAccount
metadata:
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    application-crd-id: kubeflow-pipelines
  name: proxy-agent-runner
  namespace: {{ include "common.names.namespace" . | quote }}
