{{- if .Values.proxyAgent.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    application-crd-id: kubeflow-pipelines
  name: proxy-agent-runner
  namespace: {{ include "common.names.namespace" . | quote }}
{{- end -}}

