apiVersion: batch/v1
kind: Job 
metadata:
  name: convertdataset
  namespace: pfs
spec:
  template:
    metadata:
      app: convertdataset
    spec:
      containers:
      - name: convertdataset
        image: paddlepaddle/convertdataset
        command: 
        - cd /convert/
        - python /convert/convert.py /pfs/datacenter/common
      restartPolicy: Never
